apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "bundle.fullname" . }}
    component: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}
data:
  APPLICATION_NAME: {{ .Values.application_name | quote }}
  PROVIDER_NAME: "SAP"
  PRODUCT_NAME: "SAP Fieldglass Cloud"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}-api
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "bundle.fullname" . }}
    component: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}
data:
  events.json: |-
    {
      "name": "SAP Fieldglass Business Events",
      "provider": "SAP Fieldglass",
      "description": "SAP Fieldglass Business Events",
      "events": {
        "spec": {
          "asyncapi": "1.0.0",
          "info": {
            "title": "SAP Fieldglass Business Events",
            "version": "1.0.0",
            "description": "SAP Fieldglass Business Events"
          },
          "topics": {
            "jobPosting.v1": {
              "subscribe": {
                "summary": "Job Posting",
                "payload": {
                  "type": "object",
                  "example": {
                    "StaffingOrder": {
                      "@xmlns": "jobPosting",
                      "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                      "@xsi:schemaLocation": "jobPosting https://xcore1.fgvms.com/schema/InSiteJobPostingV2.xsd",
                      "OrderId": {
                        "@validFrom": "2019-10-30",
                        "@validTo": "2019-11-15",
                        "IdValue": "JCJGJP00000014",
                        "Status": "Submitted"
                      },
                      "ReferenceInformation": {
                        "StaffingSupplierId": {
                          "IdValue": "E009"
                        },
                        "StaffingCustomerId": {
                          "IdValue": "JCJG"
                        }
                      },
                      "BusinessUnit": "JCJG",
                      "ClosedReasonName": null,
                      "OrderClassification": {
                        "@orderType": "Accountant - US",
                        "@orderStatus": "new"
                      },
                      "Comments": {
                        "Comment": null,
                        "CreatorName": null,
                        "CreateTime": null
                      },
                      "OrderContact": {
                        "@contactType": "placedBy",
                        "ContactInfo": {
                          "PersonName": {
                            "LegalName": "jane_doe",
                            "FormattedName": "Doe, Jane"
                          }
                        }
                      },
                      "RequiredResponseDate": "2019-10-31",
                      "PositionQuantity": "1",
                      "MaxSubmissionsAllowed": "3",
                      "CanSubmitJobSeeker": "no",
                      "StaffingPosition": {
                        "PositionHeader": {
                          "PositionTitle": "Accountant - US",
                          "FormattedPositionDescription": {
                            "Value": "Performs work to ensure employees are paid on time and their paychecks\nare accurate Screen time worked inputs for calculating, coding, or other\nerrors. Performs action necessary to determine pay and deductions including\nFederal and State taxes, insurance, retirement, union dues, savings and\nother deductions."
                          }
                        },
                        "PrimaryDepartment": "Network Solutions",
                        "Departments": {
                          "Department": {
                            "Code": "300",
                            "Name": "Network Solutions",
                            "Allocation": "100.000"
                          }
                        },
                        "PositionDateRange": {
                          "StartDate": "2019-10-30",
                          "ExpectedEndDate": "2019-11-15",
                          "CreateDate": "2019-10-22",
                          "SubmitDate": "2019-10-22",
                          "ClosedDate": null
                        },
                        "ServiceType": "Temp",
                        "JobType": "Full Time",
                        "ReportToPerson": {
                          "ContactInfo": {
                            "PersonName": {
                              "LegalName": "jgebo_gebo",
                              "FormattedName": "Gebo, Jeff"
                            }
                          }
                        },
                        "Coordinator": {
                          "ContactInfo": {
                            "PersonName": {
                              "LegalName": null,
                              "FormattedName": null
                            }
                          }
                        },
                        "Distributor": {
                          "ContactInfo": {
                            "PersonName": {
                              "LegalName": null,
                              "FormattedName": null
                            }
                          }
                        },
                        "WorkSite": {
                          "WorkSiteId": {
                            "Id": "111 North Canal Suite 600"
                          },
                          "Address": "111 North Canal",
                          "Address2": "Suite 600",
                          "City": "Chicago",
                          "StateCode": "IL",
                          "PostalCode": "60606"
                        },
                        "Rates": [
                          {
                            "@rateType": "bill",
                            "@rateStatus": "agreed",
                            "@payType": "Recruited",
                            "BillAmount": {
                              "@rateAmountPeriod": "Hr",
                              "@currency": "USD",
                              "$": "55.00"
                            },
                            "PayAmount": {
                              "@rateAmountPeriod": "Hr",
                              "@currency": "USD",
                              "$": "0.00"
                            },
                            "Class": "ST",
                            "Markup": null,
                            "Factor": null,
                            "BaseClass": null
                          },
                          {
                            "@rateType": "bill",
                            "@rateStatus": "agreed",
                            "@payType": "Recruited",
                            "BillAmount": {
                              "@rateAmountPeriod": "Hr",
                              "@currency": "USD",
                              "$": "82.50"
                            },
                            "PayAmount": {
                              "@rateAmountPeriod": "Hr",
                              "@currency": "USD",
                              "$": "0.00"
                            },
                            "Class": "OT",
                            "Markup": null,
                            "Factor": "1.500",
                            "BaseClass": "ST"
                          },
                          {
                            "@rateType": "bill",
                            "@rateStatus": "agreed",
                            "@payType": "Recruited",
                            "BillAmount": {
                              "@rateAmountPeriod": "Hr",
                              "@currency": "USD",
                              "$": "110.00"
                            },
                            "PayAmount": {
                              "@rateAmountPeriod": "Hr",
                              "@currency": "USD",
                              "$": "0.00"
                            },
                            "Class": "DT",
                            "Markup": null,
                            "Factor": "2.000",
                            "BaseClass": "ST"
                          }
                        ],
                        "CustomFields": {
                          "CustomField": [
                            {
                              "@name": "What's your favorite color?",
                              "@mandatory": "yes",
                              "@type": "xsd:pickList",
                              "pickList": {
                                "@isCompleteList": "yes",
                                "@totalNumberOfItems": "6",
                                "item": [
                                  "Blue",
                                  "Brown",
                                  "Green",
                                  "Purple",
                                  "Red",
                                  "Yellow"
                                ]
                              },
                              "Value": "Red",
                              "Class": "JobPosting"
                            },
                            {
                              "@name": "What's your favorite color?",
                              "@mandatory": "yes",
                              "@type": "xsd:pickList",
                              "pickList": {
                                "@isCompleteList": "yes",
                                "@totalNumberOfItems": "6",
                                "item": [
                                  "Blue",
                                  "Brown",
                                  "Green",
                                  "Purple",
                                  "Red",
                                  "Yellow"
                                ]
                              },
                              "Value": null,
                              "Class": "JobSeeker"
                            }
                          ]
                        },
                        "Quals": {
                          "Qual": {
                            "@name": "How well do you know Google Docs?",
                            "@mandatory": "yes",
                            "@type": "xsd:Ratings",
                            "Ratings": "-1"
                          }
                        },
                        "PositionRules": {
                          "AutoEngage": "no",
                          "AutoRegister": "yes",
                          "AutoActivate": "yes",
                          "PayRateRequired": "yes",
                          "ResumeRequired": "yes",
                          "JobSeekerBillRateCanExceedRequestedBillRate": "no",
                          "SupplierMustEnterRateChangeAmountsAndDurationOnJobSeekers": "no",
                          "AllowSupplierToSelectJobSeekerSite": "no"
                        },
                        "InvoiceInfo": {
                          "AutoInvoiceType": "Both",
                          "TrialEndDate": null,
                          "TravelTime": "0.000",
                          "HoursPerDay": "8.00",
                          "HoursPerWeek": "40.00",
                          "BillablePerDiem": "0.00",
                          "EstimatedAdditionalSpend": "6006.00",
                          "EstimatedTotalHours": "104.0",
                          "EstimatedExpenses": "0.000",
                          "SiteTax": "0.000",
                          "MaximumExpenses": "0.00",
                          "ExternalReqNumber": null,
                          "PurchaseOrderNumber": null
                        },
                        "SecurityIdInstruction": null,
                        "SecurityIdPattern": "[A-Z][A-Z][A-Z][A-Z][A-Z][A-Z][0-3][0-9][0-1][0-9][0-9][0-9][0-9][0-9]"
                      }
                    }
                  }
                }
              }
            },
            "jobSeeker.v1": {
              "subscribe": {
                "summary": "Job Seeker submission",
                "payload": {
                  "type": "object",
                  "required": [
                    "KEY"
                  ],
                  "example": {
                    "HumanResource": {
                      "@xmlns": "jobSeeker",
                      "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                      "@xsi:schemaLocation": "jobSeeker https://localhost/schema/InSiteJobSeeker.xsd",
                      "HumanResourceId": {
                        "@validFrom": "2019-09-27",
                        "@validTo": "2019-10-27",
                        "IdValue": null,
                        "ExternalReferenceId": "2a6d7688-714f-4eb0-a961-27f905fb9687",
                        "EntityContactInfo": {
                          "PersonName": {
                            "LegalName": "sup1234"
                          }
                        }
                      },
                      "ReferenceInformation": {
                        "StaffingSupplierId": {
                          "IdValue": ""
                        },
                        "StaffingCustomerId": {
                          "IdValue": "JCJG"
                        },
                        "OrderId": {
                          "IdValue": "JCJGJP00000014"
                        },
                        "RemitToAddress": null,
                        "WorkerPayType": null
                      },
                      "ResourceInformation": {
                        "EntityContactInfo": {
                          "PersonName": {
                            "LegalName": "Jane Doe",
                            "FirstName": "Jane",
                            "LastName": "Doe"
                          },
                          "UserName": null,
                          "SecurityId": "05179908PW",
                          "ContactMethod": {
                            "InternetEmailAddress": "testworker@sap.com"
                          }
                        },
                        "AvailabilityDate": {
                          "AvailabilityStartDate": "2019-11-01"
                        }
                      },
                      "Rates": {
                        "@rateType": "bill",
                        "@rateStatus": "agreed",
                        "BillAmount": {
                          "@rateAmountPeriod": "Hr",
                          "@currency": "USD",
                          "$": "60.00"
                        },
                        "MinBillAmount": "40.00",
                        "MaxBillAmount": "60.00",
                        "PayAmount": {
                          "@rateAmountPeriod": "Hr",
                          "@currency": "USD",
                          "$": "50.00"
                        },
                        "Class": "ST",
                        "Markup": null,
                        "Factor": null,
                        "BaseClass": null
                      },
                      "CustomFields": {
                        "CustomField": {
                          "@name": "Has this candidate previously worked for FG APIs as a permanent or\ntemporary worker?",
                          "@mandatory": "yes",
                          "@type": "xsd:pickList",
                          "pickList": {
                            "@isCompleteList": "yes",
                            "@totalNumberOfItems": "2",
                            "item": [
                              "No",
                              "Yes"
                            ]
                          },
                          "Value": "No",
                          "Class": "JobSeeker"
                        }
                      },
                      "Quals": null,
                      "HumanResourceComments": "",
                      "Profile": {
                        "Resume": {
                          "NonXMLResume": {
                            "TextResume": "VBERi0xLjQKJeLjz9MKNCAw ... [base64 encoded document] ... wYWNlL0RldmljZUdyYXkvU3VidHl",
                            "SupportingMaterials": {
                              "AttachmentReference": {
                                "@mimeType": "application/pdf",
                                "$": "test resume.pdf"
                              }
                            }
                          }
                        },
                        "AdditionalAttachment": null
                      }
                    }
                  }
                }
              }
            }
          }
        }     
      }
    }
