apiVersion: v1
kind: Service
metadata:
  name: canary-deployment-example
  labels:
    app: canary-deployment-example
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: canary-deployment-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-deployment-example-v1
  labels:
    app: canary-deployment-example
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-deployment-example
      version: v1
  template:
    metadata:
      labels:
        app: canary-deployment-example
        version: v1
    spec:
      containers:
        # replace the repository URL with your own repository (e.g. {DockerID}/http-db-service:0.0.x for Docker Hub).
        - image: jcawley5/nginx-hello
          imagePullPolicy: Always
          name: canary-deployment-example
          ports:
            - name: http
              containerPort: 80
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: canary-deployment-example
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
  service:
    host: canary-deployment-example
    name: canary-deployment-example
    port: 80
