apiVersion: v1
kind: Namespace
metadata:
  name: sftp

---

kind: Service
apiVersion: v1
metadata:
  name: sftp
  namespace: sftp
  labels:
    environment: production
spec:
  type: "LoadBalancer"
  ports:
  - name: "ssh"
    # don't use the default part, to allow the machine this runs on to be accessed using ssh
    port: 8001
    targetPort: 22
  selector:
    app: sftp
status:
  loadBalancer: {}

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: sftp
  namespace: sftp
  labels:
    environment: production
    app: sftp
spec:
  # how many pods and indicate which strategy we want for rolling update
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      environment: production
      app: sftp

  template:
    metadata:
      labels:
        environment: production
        app: sftp

    spec:
      # secrets and config
      volumes:
        - name: sftp-client-public-keys
          secret:
            secretName: sftp-client-public-keys
            defaultMode: 0600
        - name: sftp-host-keys
          secret:
            secretName: sftp-host-keys
            defaultMode: 0600
        # uncomment this and the block below to use a custom sshd_config file.
        # - name: sshd-config
        #   hostPath:
        #     path: /path/to/your/sshd_config
        #     type: File
        - name: sftp-data
          persistentVolumeClaim:
            claimName: sftp-data-pvc

      containers:
        # the sftp server itself
        - name: sftp
          # use kalioz/sftp:latest instead of atmoz/sftp:latest if you need arm compatibility.
          image: atmoz/sftp:latest
          imagePullPolicy: IfNotPresent
          # create users and dirs
          # user:password:uid:gid:directories
          args: ["myUser::::incoming,outgoing"]
          ports:
            - containerPort: 22
          volumeMounts:
            - mountPath: /home/myUser/.ssh/keys
              name: sftp-client-public-keys
              readOnly: true
            - mountPath: /etc/ssh/ssh_host_rsa_key
              name: sftp-host-keys
              subPath: ssh_host_rsa_key
              readOnly: true
            - mountPath: /etc/ssh/ssh_host_rsa_key.pub
              name: sftp-host-keys
              subPath: ssh_host_rsa_key.pub
              readOnly: true
            - mountPath: /etc/ssh/ssh_host_ed25519_key
              name: sftp-host-keys
              subPath: ssh_host_ed25519_key
              readOnly: true
            - mountPath: /etc/ssh/ssh_host_ed25519_key.pub
              name: sftp-host-keys
              subPath: ssh_host_ed25519_key.pub
              readOnly: true
            # uncomment this and the block above to use a custom sshd_config file.
            # - mountPath: /etc/ssh/sshd_config
            #   name: sshd-config
            #   readOnly: true
            - mountPath: /home/myUser
              name: sftp-data
          securityContext:
            capabilities:
              add: ["SYS_ADMIN"]
          resources: {}
            # uncomment this and remove the '{}' above to add resource limits to the pod.
            # requests:
            #   cpu: 100m
            #   memory: 64Mi
            # limits:
            #   cpu: 500m
            #   memory: 128Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftp-data-pvc
  namespace: sftp
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
