name: fieldglass-connector
version: 0.1.0
description: "Enables the preview integration of SAP Fieldglass. It is not recommended for production scenarios."
id: facbbe12-0a84-11e3-ab17-d663be873e59
displayName: "[Preview] SAP Fieldglass - Connector"
tags: preview,fieldglass,connector
labels:
  preview: "true"
providerDisplayName: SAP
longDescription: "Integrates SAP Fieldglass in preview mode by registering its REST APIs in an existing Application and enables consuming the APIs from a lambda or microservice. It is not recommended for production use."
documentationURL: https://www.fieldglass.com/
bindable: false
provisionOnlyOnce: false
imageUrl: https://github.com/jcawley5/sap-fieldglass-connector/raw/master/logos/fieldglass.png
