apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: testclient1
spec:
  grantTypes:
    - "client_credentials"
  scope: "read write"
  secretName: testclient1
  # k get oauth2clients.hydra.ory.sh api-credential -n stage -o yaml
# ---
# apiVersion: gateway.kyma-project.io/v1alpha1
# kind: APIRule
# metadata:
#   name: testfb
# spec:
#   gateway: kyma-gateway.kyma-system.svc.cluster.local
#   service:
#     name: testfb
#     port: 8080
#     host: testfb-stage.c4demo-jc1.cluster.extend.cx.cloud.sap
#   rules:
#     - path: /testfb
#       methods: ["GET"]
#       accessStrategies:
#         - handler: oauth2_introspection
#           config:
#             required_scope: ["read"]
