apiVersion: v1
kind: Secret
metadata:
  name: api-credential3
type: Opaque
data:
  client_id: dGVzdHVzZXIx
  client_secret: d2VsY29tZTE=
  # testuser1:welcome1
---
apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: api-credential3
spec:
  grantTypes:
    - "client_credentials"
  scope: "read write"
  secretName: api-credential3
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: hello-lambda
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: hello
    port: 8080
    host: hello-lambda-test.jctest.cluster.extend.cx.cloud.sap
  rules:
    - path: /hello
      methods: ["GET", "POST"]
      accessStrategies:
        - handler: oauth2_introspection
          config:
            required_scope: ["read", "write"]
